export enum PresentationType {
    Lookup = 1,
    Value_List= 2,
    Single_Value= 3,
    Dynamic= 4
}

export enum mandatory {
    Yes= 1,
    No= 2
}

export enum code {
    OWNER_NAME_Lang2ABIC_TYPE = "1",
    OWNER_ENGLISH_NAME_TYPE= "2",
    TRAFFIC_FILE_NO_TYPE= "3",
    PHONE_NUMBER_TYPE= "4",
    EMAIL_ADDRESS_TYPE= "5",
    E_WALLET_ACCOUNT_TYPE= "6",
    NATIONALITY_TYPE= "7",
    MOBILE_TYPE= "8",
    ADDRESS_TYPE= "9",
    CERTIFICATE_TYPE_TYPE= "10",
    CERTIFICATE_NO_TYPE= "11",
    OWNER_EMIRATE_TYPE= "12",
    PLATE_CATEGORY_TYPE= "13",
    PLATE_CODE_TYPE= "14",
    PLATE_NO_TYPE= "15",
    WHEEL_DRIVE_TYPE= "16",
    DRIVE_DIRECTION_TYPE= "17",
    HAS_ADVERTISMENT_TYPE= "18",
    TURBO_OR_NOT_TYPE= "19",
    WIDTH_TYPE= "20",
    HEIGHT_TYPE= "21",
    LENGTH_TYPE= "22",
    NUMBER_OF_LEDS_TYPE= "23",
    HANDBRAKE_LOCATION_TYPE= "24",
    CHASSIS_NO_TYPE= "25",
    VEHICLE_CLASS_TYPE= "26",
    ENGINE_NO_TYPE= "27",
    ENGINE_SIZE_TYPE= "28",
    HOURSE_POWER_TYPE= "29",
    BODY_TYPE_TYPE= "30",
    CYLINDERS_TYPE= "31",
    AXLES_NUMBER_TYPE= "32",
    PLATE_ORIGIN_TYPE= "33",
    ODOMETER_OLD_READING_TYPE= "34",
    ODOMETER_NEW_READING_TYPE= "35",
    FUEL_TYPE= "36",
    UNLOADED_WEIGHT_TYPE= "37",
    LOADED_WEIGHT_TYPE= "38",
    NO_OF_DOORS_TYPE= "39",
    NO_OF_SEATS_TYPE= "40",
    VEHICLE_MAKE_TYPE= "41",
    VEHICLE_MODEL_TYPE= "42",
    MODEL_YEAR_TYPE= "43",
    COLOR_TYPE= "44",
    VEHICLE_ORIGIN_TYPE= "45",
    COLOR_TYPE_TYPE= "46",
    GEAR_TYPE_TYPE= "47",
    OPERATOR_VEHICLE_RISK_RATING_TYPE= "48",
    PLATE_DETAILS= "49",
    TOKEN_NO= "50",
    LANE_NO= "51",
    CERTIFICATE_DATE_TYPE= "52",
    TRANSACTION_NO= "53",
    PLATE_EMIRATE= "54",
    AXLES_NUMBER= "55",
    IS_GCC= "56",
    IS_VIP_TYPE= "57",
    NO_OF_VEHICLES_TYPE= "58",
    OWNER_TYPE_TYPE= "59",
    REGISTRATION_EXPIRY_TYPE= "60",
    LANGUAGE= "61",
    VEHICLE_NEED_TEST= "62",
    VEHICLE_MODEL_STATUS= "63",
    VEHICLE_MAKE_STATUS= "64",
    IS_AUTHORIZED_ODOMETER= "65"
}

export enum field {
    value ='value',
    vehicle_Element_Values = 'vehicleElementValues',
    vehicle_Class = 'vehicleClass',
    country = 'country',
    vehicle_Make = 'vehicleMake',
    vehicle_Model = 'vehicleModel',
    plate_Category = 'plateCategory',
    plate_Code = 'plateCode',
    emirate = 'emirate',
    vehicle_Description = 'vehicleDescription'
}